language: php
php:
- 7.3
before_script:
- composer self-update
- composer install --no-interaction
script:
-
before_create:
- openssl aes-256-cbc -K $encrypted_a48597c1c1ce_key -iv $encrypted_a48597c1c1ce_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
before_deploy:
- openssl aes-256-cbc -K $encrypted_a48597c1c1ce_key -iv $encrypted_a48597c1c1ce_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "HostName dev.akhmad.id\n\tStrictHostKeyChecking no\n\t"User deploy >> ~/.ssh/config
deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: backend
before_install:
- openssl aes-256-cbc -K $encrypted_a48597c1c1ce_key -iv $encrypted_a48597c1c1ce_iv
  -in deploy_rsa.enc -out deploy_rsa -d
